# Generated by Django 5.0.2 on 2024-03-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category_Name", models.CharField(max_length=100, unique=True)),
                ("Slug", models.CharField(max_length=100, unique=True)),
                ("Description", models.TextField(max_length=255)),
                (
                    "Cat_Image",
                    models.ImageField(blank=True, upload_to="photos/Categories"),
                ),
            ],
        ),
    ]
