# Generated by Django 5.0.2 on 2024-03-14 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Category", "0002_alter_category_cat_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
